### ISSUE TITLE
Add an endpoint for fetching a single event from our API

### ISSUE THREAD

**Issue by mattias-persson** [happypixels/eventfinder#14]

**Comment by mattias-persson** [comment]
@robbinfellow We should probably use slugs to retrieve events to make the URLs prettier, so the first step might be to implement https://github.com/cviebrock/eloquent-sluggable.

- Make the events sluggable
- Add an EventController
- Map a GET-route to the Show-method of the EventController
- Tests

**Comment by robbinfellow** [comment]
Done in 9feb5cb @mattias-persson 🚀

**Comment by mattias-persson** [comment]
@robbinfellow Sweet! Only one thing, we want the backend to serve as an API, so we don't want to return a view from the controller. We only want to return an array containing the event. Something like this `return ['event' => $event];`.
Also, I think it's possible to do Route Model binding with the sluggable package for cleaner syntax, see https://github.com/cviebrock/eloquent-sluggable/blob/master/ROUTE-MODEL-BINDING.md.

**Comment by robbinfellow** [comment]
Fixed in eee65a1 @mattias-persson 

(forgot to tag the issue on the commit message 😴 )

**Comment by robbinfellow** [comment]
Fixed in 72c2b66. 

Maybe we should use `Route::apiResource()` instead of `Route::resource()` in the future as we allow more routes. @mattias-persson

**Comment by mattias-persson** [comment]
@robbinfellow That's a good idea but we can change that later, it's not a problem as long as we limit the open routes with the `only()`-method. Nice work!

**Comment by mattias-persson** [comment]
A couple of more things:

- Test that the entire event is returned
- Rename the test to GetSingleEventTest or similar to remove confusion between the agent-fetching and our API 
- Test 404 response

**Comment by robbinfellow** [comment]
Improved testing in c00a8fa.

Didn't test that the entire event is returned as discussed in slack with @mattias-persson.

**Comment by mattias-persson** [comment]
Looks perfect! 🎉
